In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('file.csv')
df

,Order ID,Product,Quantity Ordered,Price Each,Order Date,Purchase Address
0,295665,Macbook Pro Laptop,1,1700.00,12/30/19 00:01,"136 Church St, New York City, NY 10001"
1,295666,LG Washing Machine,1,600.00,12/29/19 07:03,"562 2nd St, New York City, NY 10001"
2,295667,USB-C Charging Cable,1,11.95,12/12/19 18:21,"277 Main St, New York City, NY 10001"
3,295668,27in FHD Monitor,1,149.99,12/22/19 15:13,"410 6th St, San Francisco, CA 94016"
4,295669,USB-C Charging Cable,1,11.95,12/18/19 12:38,"43 Hill St, Atlanta, GA 30301"
...,...,...,...,...,...,...
24984,319666,Lightning Charging Cable,1,14.95,12/11/19 20:58,"14 Madison St, San Francisco, CA 94016"
24985,319667,AA Batteries (4-pack),2,3.84,12/01/19 12:01,"549 Willow St, Los Angeles, CA 90001"
24986,319668,Vareebadd Phone,1,400.00,12/09/19 06:43,"273 Wilson St, Seattle, WA 98101"
24987,319669,Wired Headphones,1,11.99,12/03/19 10:39,"778 River St, Dallas, TX 75001"
24988,319670,Bose SoundSport Headphones,1,99.99,12/21/19 21:45,"747 Chestnut St, Los Angeles, CA 90001"

In [9]:
df.tail(10)

,Order ID,Product,Quantity Ordered,Price Each,Order Date,Purchase Address
24979,319661,AAA Batteries (4-pack),1,2.99,12/11/19 21:24,"691 West St, Portland, ME 04101"
24980,319662,Bose SoundSport Headphones,1,99.99,12/31/19 19:07,"939 8th St, San Francisco, CA 94016"
24981,319663,Flatscreen TV,1,300.00,12/07/19 08:25,"334 12th St, Atlanta, GA 30301"
24982,319664,ThinkPad Laptop,1,999.99,12/30/19 01:06,"767 2nd St, San Francisco, CA 94016"
24983,319665,iPhone,1,700.00,12/15/19 11:13,"377 1st St, Atlanta, GA 30301"
24984,319666,Lightning Charging Cable,1,14.95,12/11/19 20:58,"14 Madison St, San Francisco, CA 94016"
24985,319667,AA Batteries (4-pack),2,3.84,12/01/19 12:01,"549 Willow St, Los Angeles, CA 90001"
24986,319668,Vareebadd Phone,1,400.00,12/09/19 06:43,"273 Wilson St, Seattle, WA 98101"
24987,319669,Wired Headphones,1,11.99,12/03/19 10:39,"778 River St, Dallas, TX 75001"
24988,319670,Bose SoundSport Headphones,1,99.99,12/21/19 21:45,"747 Chestnut St, Los Angeles, CA 90001"

In [10]:
df.Product

0                Macbook Pro Laptop
1                LG Washing Machine
2              USB-C Charging Cable
3                  27in FHD Monitor
4              USB-C Charging Cable
                    ...
24984      Lightning Charging Cable
24985         AA Batteries (4-pack)
24986               Vareebadd Phone
24987              Wired Headphones
24988    Bose SoundSport Headphones
Name: Product, Length: 24989, dtype: object

In [12]:
df['Price Each']

0        1700.00
1         600.00
2          11.95
3         149.99
4          11.95
          ...
24984      14.95
24985       3.84
24986     400.00
24987      11.99
24988      99.99
Name: Price Each, Length: 24989, dtype: float64

In [13]:
df2 = pd.read_html('https://www.banki.ru/products/hypothec/search/?ysclid=laxytbc3pw965739608')
df2

[                                                  0  \
 0                                           Продукт
 1                                  Семейная ипотека
 2                           Ипотека с господдержкой
 3                                     Готовое жилье
 4                                  Льготная ипотека
 5                                   С господдержкой
 6                            Господдержка 2020–2022
 7                                  Льготная ипотека
 8                                 Госпрограмма 2020
 9                Новостройка с господдержкой — 2020
 10                         Госпрограмма 2020 — 2022
 11                          Льготная ипотека — 2020
 12  Льготная ипотека на новостройку с господдержкой
 13                          Льготная ипотека — 2020
 14                                    Готовое жилье
 15                          Ипотека с господдержкой

                                  1        2         3          4  \
 0                             Банк   Ставка    Платеж        NaN
 1                      Газпромбанк   5,30 %  10 150 ₽  Подробнее
 2                       Альфа-Банк   6,00 %  10 746 ₽  Подробнее
 3   Московский Индустриальный Банк   9,95 %  14 426 ₽  Подробнее
 4                      Банк ДОМ.РФ   6,00 %  10 746 ₽  Подробнее
 5                    Банк Открытие   6,30 %  11 008 ₽  Подробнее
 6                             РНКБ   6,00 %  10 746 ₽  Подробнее
 7                          Росбанк   4,95 %   9 858 ₽  Подробнее
 8                    Промсвязьбанк   6,35 %  11 052 ₽  Подробнее
 9                       Совкомбанк   5,00 %   9 899 ₽  Подробнее
 10                    Абсолют Банк   6,50 %  11 184 ₽  Подробнее
 11       Московский Кредитный Банк   6,46 %  11 148 ₽  Подробнее
 12  Ипотечный консультант Банки.ру   6,30 %  11 008 ₽  Подробнее
 13                Металлинвестбанк   6,30 %  11 008 ₽  Подробнее
 14   Банк Жилищного Финансирования  10,70 %  15 178 ₽  Подробнее
 15                    Банк Уралсиб   6,59 %  11 263 ₽  Подробнее

                   5
 0               NaN
 1   Оставить заявку
 2   Оставить заявку
 3   Оставить заявку
 4   Оставить заявку
 5   Оставить заявку
 6   Оставить заявку
 7   Оставить заявку
 8   Оставить заявку
 9   Оставить заявку
 10  Оставить заявку
 11  Оставить заявку
 12  Оставить заявку
 13  Оставить заявку
 14  Оставить заявку
 15  Оставить заявку  ]

In [15]:
len(df2)

1

In [16]:
df2[0]

,0,1,2,3,4,5
0,Продукт,Банк,Ставка,Платеж,NaN,NaN
1,Семейная ипотека,Газпромбанк,"5,30 %",10 150 ₽,Подробнее,Оставить заявку
2,Ипотека с господдержкой,Альфа-Банк,"6,00 %",10 746 ₽,Подробнее,Оставить заявку
3,Готовое жилье,Московский Индустриальный Банк,"9,95 %",14 426 ₽,Подробнее,Оставить заявку
4,Льготная ипотека,Банк ДОМ.РФ,"6,00 %",10 746 ₽,Подробнее,Оставить заявку
5,С господдержкой,Банк Открытие,"6,30 %",11 008 ₽,Подробнее,Оставить заявку
6,Господдержка 2020–2022,РНКБ,"6,00 %",10 746 ₽,Подробнее,Оставить заявку
7,Льготная ипотека,Росбанк,"4,95 %",9 858 ₽,Подробнее,Оставить заявку
8,Госпрограмма 2020,Промсвязьбанк,"6,35 %",11 052 ₽,Подробнее,Оставить заявку
9,Новостройка с господдержкой — 2020,Совкомбанк,"5,00 %",9 899 ₽,Подробнее,Оставить заявку
10,Госпрограмма 2020 — 2022,Абсолют Банк,"6,50 %",11 184 ₽,Подробнее,Оставить заявку
11,Льготная ипотека — 2020,Московский Кредитный Банк,"6,46 %",11 148 ₽,Подробнее,Оставить заявку
12,Льготная ипотека на новостройку с господдержкой,Ипотечный консультант Банки.ру,"6,30 %",11 008 ₽,Подробнее,Оставить заявку
13,Льготная ипотека — 2020,Металлинвестбанк,"6,30 %",11 008 ₽,Подробнее,Оставить заявку
14,Готовое жилье,Банк Жилищного Финансирования,"10,70 %",15 178 ₽,Подробнее,Оставить заявку
15,Ипотека с господдержкой,Банк Уралсиб,"6,59 %",11 263 ₽,Подробнее,Оставить заявку

In [18]:
df2 = pd.read_html('https://www.banki.ru/products/hypothec/search/?ysclid=laxytbc3pw965739608')
df2

[                                                  0  \
 0                                           Продукт
 1                                  Семейная ипотека
 2                           Ипотека с господдержкой
 3                                     Готовое жилье
 4                                  Льготная ипотека
 5                                   С господдержкой
 6                            Господдержка 2020–2022
 7                                  Льготная ипотека
 8                                 Госпрограмма 2020
 9                Новостройка с господдержкой — 2020
 10                         Госпрограмма 2020 — 2022
 11                          Льготная ипотека — 2020
 12  Льготная ипотека на новостройку с господдержкой
 13                          Льготная ипотека — 2020
 14                                    Готовое жилье
 15                          Ипотека с господдержкой

                                  1        2         3          4  \
 0                             Банк   Ставка    Платеж        NaN
 1                      Газпромбанк   5,30 %  10 150 ₽  Подробнее
 2                       Альфа-Банк   6,00 %  10 746 ₽  Подробнее
 3   Московский Индустриальный Банк   9,95 %  14 426 ₽  Подробнее
 4                      Банк ДОМ.РФ   6,00 %  10 746 ₽  Подробнее
 5                    Банк Открытие   6,30 %  11 008 ₽  Подробнее
 6                             РНКБ   6,00 %  10 746 ₽  Подробнее
 7                          Росбанк   4,95 %   9 858 ₽  Подробнее
 8                    Промсвязьбанк   6,35 %  11 052 ₽  Подробнее
 9                       Совкомбанк   5,00 %   9 899 ₽  Подробнее
 10                    Абсолют Банк   6,50 %  11 184 ₽  Подробнее
 11       Московский Кредитный Банк   6,46 %  11 148 ₽  Подробнее
 12  Ипотечный консультант Банки.ру   6,30 %  11 008 ₽  Подробнее
 13                Металлинвестбанк   6,30 %  11 008 ₽  Подробнее
 14   Банк Жилищного Финансирования  10,70 %  15 178 ₽  Подробнее
 15                    Банк Уралсиб   6,59 %  11 263 ₽  Подробнее

                   5
 0               NaN
 1   Оставить заявку
 2   Оставить заявку
 3   Оставить заявку
 4   Оставить заявку
 5   Оставить заявку
 6   Оставить заявку
 7   Оставить заявку
 8   Оставить заявку
 9   Оставить заявку
 10  Оставить заявку
 11  Оставить заявку
 12  Оставить заявку
 13  Оставить заявку
 14  Оставить заявку
 15  Оставить заявку  ]

In [20]:
df2[0]

,0,1,2,3,4,5
0,Продукт,Банк,Ставка,Платеж,NaN,NaN
1,Семейная ипотека,Газпромбанк,"5,30 %",10 150 ₽,Подробнее,Оставить заявку
2,Ипотека с господдержкой,Альфа-Банк,"6,00 %",10 746 ₽,Подробнее,Оставить заявку
3,Готовое жилье,Московский Индустриальный Банк,"9,95 %",14 426 ₽,Подробнее,Оставить заявку
4,Льготная ипотека,Банк ДОМ.РФ,"6,00 %",10 746 ₽,Подробнее,Оставить заявку
5,С господдержкой,Банк Открытие,"6,30 %",11 008 ₽,Подробнее,Оставить заявку
6,Господдержка 2020–2022,РНКБ,"6,00 %",10 746 ₽,Подробнее,Оставить заявку
7,Льготная ипотека,Росбанк,"4,95 %",9 858 ₽,Подробнее,Оставить заявку
8,Госпрограмма 2020,Промсвязьбанк,"6,35 %",11 052 ₽,Подробнее,Оставить заявку
9,Новостройка с господдержкой — 2020,Совкомбанк,"5,00 %",9 899 ₽,Подробнее,Оставить заявку
10,Госпрограмма 2020 — 2022,Абсолют Банк,"6,50 %",11 184 ₽,Подробнее,Оставить заявку
11,Льготная ипотека — 2020,Московский Кредитный Банк,"6,46 %",11 148 ₽,Подробнее,Оставить заявку
12,Льготная ипотека на новостройку с господдержкой,Ипотечный консультант Банки.ру,"6,30 %",11 008 ₽,Подробнее,Оставить заявку
13,Льготная ипотека — 2020,Металлинвестбанк,"6,30 %",11 008 ₽,Подробнее,Оставить заявку
14,Готовое жилье,Банк Жилищного Финансирования,"10,70 %",15 178 ₽,Подробнее,Оставить заявку
15,Ипотека с господдержкой,Банк Уралсиб,"6,59 %",11 263 ₽,Подробнее,Оставить заявку

In [21]:
import os

In [31]:
df_oll = pd.DataFrame()
for f in os.listdir(path = '.'):
                    print(f)

.ipynb_checkpoints
2 - Чтение и базовые операции.html
2 - Чтение и базовые операции.ipynb
file.csv
Чтение и БО.ipynb